pring.application.name=EmployeeManagementSystem_MVC6

spring.mvc.view.prefix=/WEB-INF/Pages/
spring.mvc.view.suffix=.jsp

# ===========================
# ORACLE DATABASE SETTINGS
# ===========================
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=system
spring.datasource.password=123

# ===========================
# JPA / HIBERNATE SETTINGS
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=4044