spring.application.name=ProductManagementSystem_Datasource_Runner

 
# DataSource cfg
app.ds.driver=oracle.jdbc.driver.OracleDriver
app.ds.url=jdbc:oracle:thin:@localhost:1521:orcl    
app.ds.username=nit
app.ds.password=raj

