spring.application.name=MS2-EmployeeService
server.port=6996

# Eureka (enable when server is running)
# eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Actuator endpoints exposure
management.endpoints.web.exposure.include=health,refresh
management.endpoint.health.show-details=always
